spring:
  application:
    name: SPK Profile Matching
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spk_pm
    username: root
    password: starsyndrome

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

module-name: TemanMelati
api-version: 9.9.9